sudo: required
dist: trusty

language: java
jdk:
  - oraclejdk8
install:
  - export MAVEN_SKIP_RC=true
  - export MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=512m"
  - "export PATH=`pwd`/bin:$PATH"
addons:
  sonarcloud:
    organization: "holisticon-github"
    token:
      secure: "y6z4L3+A1ArQwyatMeezel54QiXD+OdTYFDzC3/mXq38u37nuE2O0ww85xaK4AhbooxJWdni2RUArjic0niZGD8m2yJbf/mfZdCGy0UC6Ogiw+q8k124FvCHItX2RyIGBTzlKziTYdq+nPWRtOlumPKj6Q/8PqBeWcqp1oiplm20gtcTy8mDPWxW2hlhDfIc3xdpK7N0eCGTjboF+aFdVQygp9KIFBIqqxgSHSfa5jS9PokvvdDxhseb7wtKX6eQ+B7gKwEijHhg/2FaQ8rAbxnI6KkzLQ4fcvpaeTZtYk4v616Z4X4S1kFecWF/1c3+o44/2YsswWuRLrOmHiVuvjkUCpdfY2v1cEVBEfBajkM7NdBoCnxKhd4QEMEeK0aGQCBsgYXWnhF3hwTnGlL53/RF3RoObp6y4VKH/J0umidLpTk0G25xbOJsDfD/Yxey3UUyMxg00L4k9fZAoZwYzkCnb3hUAJ2XS9+lm4CUyn+PjCt6FP5xI5KT1wxTc0FrqVU7wEdxR6IJhPQsLkKuUPA0aLT4+rU7KYG80TgCD/w8/wxH3+6gp9ndYC7zjJYSJc0SQ2r7jpSO1v0mvyqoMdaswaXfQjMoCblto0ZszVcEXu8W40826XVDVu2/sdsSVIpypmYlT5Nlv5P1YOn7W5kv3GhpbW3AqErXeBrYXvA="

script:
  - export DISPLAY=:99.0 && ./mvnw clean verify -q sonar:sonar

after_success:
  - bash <(curl -s https://codecov.io/bash)
