version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_ROOT_HOST
    ports:
      - '${DB_PORT}'
    volumes:
      - .etc/docker/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 30s
      timeout: 10s
      retries: 5
# tag::keycloak-docker-setup[]
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:12.0.4
    depends_on:
      - mysql
    ports:
      - '9090:8080'
    links:
      - mysql
# end::keycloak-docker-setup[]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      KEYCLOAK_PASSWORD: 'admin'
      KEYCLOAK_USER: 'admin'
      KEYCLOAK_LOGLEVEL: 'INFO'
      ROOT_LOGLEVEL: 'INFO'
